name: stack-beacon_argon

services:
  appdaemon:
    container_name: beacon
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    image: acockburn/appdaemon:dev 
    restart: unless-stopped 
    tty: true 
    user: "1000:1000"
    network_mode: "container:uptime-kuma"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./conf:/conf
      - ${DOCKERDATADIR}/beacon/local:/.local
      - ${DOCKERDATADIR}/beacon/cache:/.cache
      - ./uptime-kuma-api:/uptime-kuma-api
